### PR TITLE
Fix redirectTo URL parameter

### LINKED ISSUE #136: Issue with returnTo/state post callback
Having an issue with the returnTo parameter.

Here is the issue:

Start login at /node/99 -> which takes me to /user/login if there is no session -> authenticates the user against Auth0 after building the authorize URL -> callback to module -> Here it returns to /user page instead of /node/99 where i started the authentication.
I see the https://github.com/auth0/auth0-drupal/blob/master/src/Controller/AuthController.php is accepting returnTo URL, but is not redirecting back to that URL after authentication is complete and callback service is call.

### PR DESCRIPTION
**Pull request by joshcanhelp**
### Changes

- Fix `returnTo` URL parameter on login URL not redirecting after successful callback processing
- Remove `prompt=none` when redirecting for SSO
- Fix Auth0 logout URL not using Application-level redirects

### References

Closes #136 

### Testing

1) Go to the Drupal login link with a `returnTo` URL parameter set to a site URL.
2) Log in successfully.
3) Final page should be what `returnTo` was set to.

### Checklist

* [x] I ran the PHPCS Drupal coding standards:

### CODE REVIEW

File: src/Controller/AuthController.php [hunk 1]
```diff
@@ -244,12 +244,9 @@ public function login(Request $request) {
       $lockExtraSettings = "{}";
     }
 
-    $returnTo = NULL;
-    if ($request->request->has('returnTo')) {
-      $returnTo = $request->request->get('returnTo');
-    }
-    elseif ($request->query->has('returnTo')) {
-      $returnTo = $request->query->get('returnTo');
+    $returnTo = $request->request->get('returnTo', NULL);
```
Comment (joshcanhelp) [inline src/Controller/AuthController.php]: Simplified, was confusing to follow

File: src/Controller/AuthController.php [hunk 2]
```diff
@@ -410,9 +407,7 @@ public function callback(Request $request) {
     global $base_root;
     $problem_logging_in_msg = $this->t('There was a problem logging you in, sorry for the inconvenience.');
 
-    $returnTo = NULL;
-    $response = $this->checkForError($request, $returnTo);
-
+    $response = $this->checkForError($request, NULL);
```
Comment (joshcanhelp) [inline src/Controller/AuthController.php]: Can't use the redirect in state yet as we haven't verified it.

File: src/Controller/AuthController.php [hunk 3]
```diff
@@ -423,11 +418,6 @@ public function callback(Request $request) {
       'client_id'     => $this->clientId,
       'client_secret' => $this->clientSecret,
       'redirect_uri'  => "$base_root/auth0/callback",
-      'store' => NULL,
```
Comment (joshcanhelp) [inline src/Controller/AuthController.php]: These are all defaults in the SDK

File: src/Controller/AuthController.php [hunk 4]
```diff
@@ -575,7 +573,7 @@ protected function processUserLogin(Request $request, array $userInfo, $idToken,
 
     user_login_finalize($user);
 
-    if ($returnTo !== NULL && strlen($returnTo) > 0 && $returnTo[0] === '/') {
+    if ($returnTo) {
```
Comment (joshcanhelp) [inline src/Controller/AuthController.php]: The `RedirectResponse` class checks for external URLs, no need to check that this is a relative path.

File: src/Controller/AuthController.php [hunk 5]
```diff
@@ -244,18 +244,14 @@ public function login(Request $request) {
...
-      $returnTo = $request->query->get('returnTo');
+    $returnTo = $request->request->get('returnTo', NULL);
+    if (!$returnTo) {
+      $returnTo = $request->query->get('returnTo', NULL);
     }
 
     // If supporting SSO, redirect to the hosted login page for authorization.
     if ($this->redirectForSso) {
-      $prompt = 'none';
-      return new TrustedRedirectResponse($this->buildAuthorizeUrl($prompt, $returnTo));
```
Comment (joshcanhelp) [inline src/Controller/AuthController.php]: This was setting `prompt=none` then catching the `login_required` error and redirecting again. This is unnecessary with seamless SSO.

File: src/Controller/AuthController.php [hunk 6]
```diff
@@ -292,18 +288,13 @@ public function login(Request $request) {
...
-    // If we are using SSO, we need to logout completely from Auth0,
-    // otherwise they will just logout of their client.
-    return new TrustedRedirectResponse($auth0Api->get_logout_link(
-        $base_root,
-        $this->redirectForSso ? NULL : $this->clientId)
-    );
+    // Redirect to Auth0 to log out.
+    $auth0Api = new Authentication($this->domain, $this->clientId);
+    $frontPageUrl = Url::fromRoute('<front>', [], ['absolute' => TRUE]);
+    $logoutUrl = $auth0Api->get_logout_link($frontPageUrl, $this->clientId);
```
Comment (joshcanhelp) [inline src/Controller/AuthController.php]: Always add the `clientId` to the logout URL to use Application-level redirects.

File: src/Controller/AuthController.php [hunk 7]
```diff
@@ -244,18 +244,14 @@ public function login(Request $request) {
       $lockExtraSettings = "{}";
     }
 
-    $returnTo = NULL;
-    if ($request->request->has('returnTo')) {
-      $returnTo = $request->request->get('returnTo');
-    }
-    elseif ($request->query->has('returnTo')) {
-      $returnTo = $request->query->get('returnTo');
+    $returnTo = $request->request->get('returnTo', NULL);
```
Comment (lbalmaceda) [inline src/Controller/AuthController.php]: This would be the same. (remove the if below) Does it look better to you or do you rather use the if?

```suggestion
    $returnTo = $request->request->get('returnTo', $request->query->get('returnTo', NULL));
```

File: src/Controller/AuthController.php (hunk 5 above)
Comment (lbalmaceda) [reply src/Controller/AuthController.php]: Is seamless SSO enabled by default and for every tenant? or how will this change affect those with that setting disabled? e.g. shouldn't you check for that setting's value before making this decision?

File: src/Controller/AuthController.php (hunk 6 above)
Comment (lbalmaceda) [reply src/Controller/AuthController.php]: this change should as well be documented. Previously, users were required to whitelist the logout url in the TENANT settings. When this is merged, users are going to be required to whitelist it in the APPLICATION settings. Make sure you update docs. 👍

File: src/Controller/AuthController.php [hunk 8]
```diff
@@ -292,18 +288,13 @@ public function login(Request $request) {
    *   The response after logout.
    */
   public function logout() {
-    global $base_root;
-
-    $auth0Api = new Authentication($this->domain, $this->clientId);
-
     user_logout();
```
Comment (lbalmaceda) [inline src/Controller/AuthController.php]: What's different with this and the call below?  Will the order have any effect? What if one of the 2 fails?

File: src/Controller/AuthController.php (hunk 2 above)
Comment (lbalmaceda) [reply src/Controller/AuthController.php]: I don't understand your comment. The diff is the same (1 line vs 2 lines, but same logic)

File: src/Controller/AuthController.php (hunk 3 above)
Comment (lbalmaceda) [reply src/Controller/AuthController.php]: Meaning this is already being set to `null` in a different file?

File: src/Controller/AuthController.php [hunk 9]
```diff
@@ -462,6 +446,15 @@ public function callback(Request $request) {
       return $this->failLogin($problem_logging_in_msg, $this->t('Failed to validate JWT: @exception', ['@exception' => $e->getMessage()]));
     }
 
+    // State value is validated in $this->auth0->getUser() above.
```
Comment (lbalmaceda) [inline src/Controller/AuthController.php]: would it make sense to extract that to a different method? (getUser vs verifyState)

File: src/Controller/AuthController.php (hunk 5 above)
Comment (joshcanhelp) [reply src/Controller/AuthController.php]: This redirects to check, then re-redirects if they need to login. Poor experience for the majority of customers, IMHO. Just redirecting and letting the ULP handle is simpler and more standard.

File: src/Controller/AuthController.php (hunk 6 above)
Comment (joshcanhelp) [reply src/Controller/AuthController.php]: You're correct, I should have tested more thoroughly here. I thought it would also accept the tenant logout URL as well but it does not. I'll revert this change and save for a major.

File: src/Controller/AuthController.php (hunk 2 above)
Comment (joshcanhelp) [reply src/Controller/AuthController.php]: Just that we can't set the actual returnTo URL yet so the variable assignment is confusing (instead of just using `NULL` directly).

File: src/Controller/AuthController.php (hunk 3 above)
Comment (joshcanhelp) [reply src/Controller/AuthController.php]: Meaning the SDK constructor sets the same values as what we are using here:

https://github.com/auth0/auth0-PHP/blob/master/src/Auth0.php#L343-L356

File: src/Controller/AuthController.php (hunk 9 above)
Comment (joshcanhelp) [reply src/Controller/AuthController.php]: It's using the SDK so cannot be changed here.

**Comment by joshcanhelp** [comment]
@lbalmaceda - Yes, tests would be great but there is no testing framework set up for this module yet.
